spring.application.name=little-creatures-backend
spring.datasource.url=jdbc:mysql://localhost:3306/little_creatures_db
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true